// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.CreateShipment.CreateShipmentHandler.HandleAsync(Modules.Shipments.Features.Features.CreateShipment.CreateShipmentRequest,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Shipments.Features.Features.Shared.Responses.ShipmentResponse}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.CancelShipment.CancelShipmentHandler.HandleAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Common.Domain.Results.Success}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.CreateShipment.Events.CreateCarrierEventHandler.HandleAsync(Modules.Shipments.Features.Features.CreateShipment.Events.ShipmentCreatedEvent,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.CreateShipment.Events.UpdateStockEventHandler.HandleAsync(Modules.Shipments.Features.Features.CreateShipment.Events.ShipmentCreatedEvent,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.DeliverShipment.DeliverShipmentHandler.HandleAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Common.Domain.Results.Success}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.DispatchShipment.DispatchShipmentHandler.HandleAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Common.Domain.Results.Success}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.ProcessShipment.ProcessShipmentHandler.HandleAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Common.Domain.Results.Success}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.ReceiveShipment.ReceiveShipmentHandler.HandleAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Common.Domain.Results.Success}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Shipments.Features.Features.TransitShipment.TransitShipmentHandler.HandleAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Common.Domain.Results.Result{Modules.Common.Domain.Results.Success}}")]
